name: run main.py

on:
  schedule:
    - cron: '0 5 * * *' # runs every day at 5 am UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script recurrent_tasks
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: python main.py recurrent_tasks
